spring:
  application:
    name: vibetalk

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://13.124.208.108:3306/vibe_talk?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8mb4&useUnicode=true
    username: root
    password: ehdwns927!
    hikari:
      max-lifetime: 300000
      idle-timeout: 60000
      validation-timeout: 3000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: "*"

  websocket:
    endpoint: /ws

server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret: mysupersecretkeythatshouldbelongandsecure1234

app:
  external:
    url: https://7834498ad334.ngrok-free.app
  websocket:
    url: wss://7834498ad334.ngrok-free.app/ws
